services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: "${POSTGRES_HOST}"
      DB_NAME: "${POSTGRES_DB}"
      DB_USERNAME: "${POSTGRES_USERNAME}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_PORT: "${POSTGRES_PORT}"
    volumes:
      - .:/app
    ports:
      - "3001:3001"

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      TZ: "Asia/Bangkok"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres:

